### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by HadrienLG** [lexaux/esphome-clock#1]
I'm interested in building an clock linked to my ESPHome setup, and wanted to check on your schematics, but your link seems to be dead: [https://easyeda.com/editor#id=325fd9a46f6f46d78fa998621406d1d9|1ad2b90e5d274dfcbf01dab694824f95](https://easyeda.com/editor#id=325fd9a46f6f46d78fa998621406d1d9%7C1ad2b90e5d274dfcbf01dab694824f95)
Could you please update it of add a PDF/PNG export of it?

**Comment by lexaux** [comment]
Hey @HadrienLG, thanks for spotting this. 

Link updated in README. It should be https://oshwlab.com/lexaux/dimming-esp-clock-auto now. 

Please let me know if you're still having troubles accessing it, and I'll share materialized designs. 

P.S. I liked this project a lot; created like a dozen of those, and set up in each room and sent to friends. Good luck!
